applications:
  - name: pat
    namespace: pat
    repoURL: https://github.com/timothywashburn/pat-api
    branch: main
    path: helm
    images:
      - alias: client
        image: kyrokrypt/pat-app
        pullSecret: pat/dockerhub-registry
      - alias: server
        image: kyrokrypt/pat-api
        pullSecret: pat/dockerhub-registry
  - name: clubhive
    namespace: clubhive
    repoURL: https://github.com/timothywashburn/clubhive
    branch: main
    path: helm
    valuesFile: values-prod.yaml
    images:
      - alias: client
        image: kyrokrypt/clubhive-client-main
        pullSecret: clubhive/dockerhub-registry
      - alias: server
        image: kyrokrypt/clubhive-server-main
        pullSecret: clubhive/dockerhub-registry
  - name: clubhive-dev
    namespace: clubhive-dev
    repoURL: https://github.com/timothywashburn/clubhive
    branch: dev
    path: helm
    values:
      ingress:
        host: https://d.test.timothyw.dev
      mongodb:
        port: 30018
    images:
      - alias: client
        image: kyrokrypt/clubhive-client-dev
        pullSecret: clubhive-dev/dockerhub-registry
      - alias: server
        image: kyrokrypt/clubhive-server-dev
        pullSecret: clubhive-dev/dockerhub-registry
  - name: overleaf
    namespace: overleaf
    repoURL: https://github.com/timothywashburn/overleaf
    branch: main
    path: helm