{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .repoURL }}
    path: {{ .path }}
    targetRevision: {{ .branch }}
    helm:
      {{- if .valuesFile }}
      valueFiles:
        - {{ .valuesFile }}
      {{- end }}
      {{- if .values }}
      values: |
{{ toYaml .values | indent 8 }}
      {{- end }}
      {{- if .images }}
      parameters:
        {{- range .images }}
        - name: image.{{ .alias }}.name
          value: {{ .image }}
        {{- end }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/storageClassName
    - kind: Secret
      jsonPointers:
        - /data
        - /stringData
{{- end }}
