{{- if and .Values.longhorn.ingress_and_auth.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: longhorn-oauth
  namespace: longhorn-system
spec:
  forwardAuth:
    address: http://oauth2-proxy.longhorn-system.svc.cluster.local:4180
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.hosts.longhorn }}`) && PathPrefix(`/oauth2`)
      priority: 20
      services:
        - name: oauth2-proxy
          port: 4180
    - kind: Rule
      match: Host(`{{ .Values.hosts.longhorn }}`)
      priority: 10
      middlewares:
        - name: longhorn-oauth
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: longhorn-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: longhorn-https-redirect
  namespace: longhorn-system
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-http
  namespace: longhorn-system
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.hosts.longhorn }}`) && !PathPrefix(`/.well-known/acme-challenge/`)
      middlewares:
        - name: longhorn-https-redirect
      services:
        - name: longhorn-frontend
          port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls
  namespace: longhorn-system
spec:
  secretName: longhorn-tls
  issuerRef:
    name: {{ .Values.cert_manager.cert_issuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.hosts.longhorn }}
{{- end }}