global:
  dashboardDomain: d.k8s.timothyw.dev
  argoCDDomain: d.argo.timothyw.dev
  grafanaDomain: d.grafana.timothyw.dev
  longhornDomain: d.longhorn.timothyw.dev
  loadBalancerIP: "132.249.242.21"
  certManagerEmail: timothyrwashburn@gmail.com

argocd:
  repository: https://github.com/timothywashburn/t8s
  branch: chore/stabilize

infrastructure:
  traefik:
    rbacFix:
      enabled: true
  metallb:
    enabled: true
  dashboard:
    enabled: true
  argocd:
    enabled: true
  monitoring:
    enabled: true
  longhorn:
    enabled: true